# Generated by Django 4.2.1 on 2023-06-24 15:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ANNOTATOR', 'ANNOTATOR'), ('PROJECT MANAGER', 'PROJECT MANAGER')], max_length=20)),
                ('dob', models.DateField(null=True)),
                ('mobile_number', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('zipcode', models.CharField(max_length=6, null=True)),
                ('primary_language', models.CharField(choices=[('Telugu', 'Telugu'), ('Hindi', 'Hindi'), ('Tamil', 'Tamil'), ('Kannada', 'Kannada'), ('Marathi', 'Marathi'), ('Other', 'Others')], max_length=20, null=True)),
                ('english_proficiency', models.CharField(choices=[('basic', 'Basic'), ('good', 'Good Command'), ('v_good', 'Very Good Command'), ('ex', 'Excellent Command'), ('fluent', 'Fluent'), ('native', 'Native Speaker')], max_length=20, null=True)),
                ('education', models.CharField(choices=[('10th', '10th Standard'), ('12th', '12th Standard'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree")], max_length=20, null=True)),
                ('prior_experience', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
